import React from "react";
import {AbsoluteFill, interpolate, useCurrentFrame} from "remotion";
import {Eyebrow} from "../components/Type";
import {BEAT, DISPLAY, MONO, DIM, FAINT, GRAY, NAVY_2, TEAL, WHITE} from "../theme";

const STEPS = [
  ["01 · KEYS", "ECDSA and BLS", "Generated by the operator, signing the node into the network."],
  ["02 · WHITELIST", "Access is granted", "The operator set is permissioned — you ask before a node can register."],
  ["03 · REGISTRATION", "Through EigenLayer", "Which is why the operator set is publicly readable on-chain."],
  ["04 · TELEMETRY", "A metrics sidecar", "OpenTelemetry, and operators can point it at collectors of their own."],
];

/** 22 - 26 s. Powered shows who buys proofs; this shows who makes them. */
export const Operators: React.FC = () => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill style={{padding: "0 130px", justifyContent: "center", gap: 46}}>
      <div>
        <Eyebrow>THE SUPPLY SIDE</Eyebrow>
        <div style={{fontFamily: DISPLAY, fontWeight: 700, fontSize: 62, letterSpacing: "-0.03em", marginTop: 18, color: WHITE}}>
          And who <span style={{color: TEAL}}>makes</span> the proofs.
        </div>
      </div>

      <div style={{display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 20}}>
        {STEPS.map(([step, title, text], i) => {
          const t = frame - 14 - i * (BEAT / 2);
          const o = interpolate(t, [0, 10], [0, 1], {extrapolateLeft: "clamp", extrapolateRight: "clamp"});
          const y = interpolate(t, [0, 14], [22, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"});
          return (
            <div key={step} style={{
              background: NAVY_2, border: "1px solid #22314F", padding: 28,
              opacity: o, transform: `translateY(${y}px)`,
            }}>
              <div style={{fontFamily: MONO, fontSize: 13, letterSpacing: "0.18em", color: TEAL}}>{step}</div>
              <div style={{fontFamily: DISPLAY, fontWeight: 700, fontSize: 26, color: WHITE, margin: "14px 0 10px", letterSpacing: "-0.02em"}}>
                {title}
              </div>
              <div style={{fontFamily: MONO, fontSize: 14, lineHeight: 1.6, color: GRAY}}>{text}</div>
            </div>
          );
        })}
      </div>

      <div style={{fontFamily: MONO, fontSize: 16, letterSpacing: "0.16em", color: FAINT}}>
        READ STRAIGHT FROM THE CHAIN — NO API KEY, NO PERMISSION
      </div>
    </AbsoluteFill>
  );
};
