import assert from 'node:assert/strict';
import {copyFile, readFile, writeFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = resolve(process.argv[2] ?? resolve(root, '../site/data'));
const site = JSON.parse(await readFile(resolve(dataDir, 'stats.json'), 'utf8'));
const seed = JSON.parse(await readFile(resolve(dataDir, 'seed.json'), 'utf8'));
const creators = seed.creators.filter((creator) => !creator.suspended);
assert.equal(creators.length, site.creators);
assert.equal(site.last_week, 22);
const weeks = (creator) => new Set(creator.contributions.map((item) => item.week_label));
const avatars = resolve(root, 'public/avatars');
const siteAvatars = resolve(dataDir, '../avatars');
const copied = [];
for (const creator of creators) {
  const file = `${creator.display_handle.toLowerCase()}.jpg`;
  if (!existsSync(resolve(avatars, file)) && existsSync(resolve(siteAvatars, file))) {
    await copyFile(resolve(siteAvatars, file), resolve(avatars, file));
    copied.push(file);
  }
}
const hasAvatar = creators.filter((creator) =>
  existsSync(resolve(avatars, `${creator.display_handle.toLowerCase()}.jpg`)))
  .map((creator) => creator.display_handle.toLowerCase()).sort();
const available = new Set(hasAvatar);
const current = creators.filter((creator) => weeks(creator).has(22));
const namesFor = (tier) => current.filter((creator) => creator.contributions.some((item) =>
  item.week_label === 22 && item.tier === tier)).map((creator) => `@${creator.display_handle}`);
const record = (handle) => {
  const creator = creators.find((item) => item.display_handle.toLowerCase() === handle);
  assert(creator, `Missing creator: ${handle}`);
  const result = {};
  for (const item of creator.contributions) {
    if (item.tier === 'spotlight') result[item.week_label] = 'S';
    else if (item.tier === 'honourable_mention' && result[item.week_label] !== 'S') result[item.week_label] = 'm';
  }
  return result;
};
const endedFiveWeekAppearances = creators.filter((creator) => {
  const appeared = weeks(creator);
  return !appeared.has(22) && !appeared.has(16) && [17, 18, 19, 20, 21].every((week) => appeared.has(week));
}).map((creator) => creator.display_handle);
const stats = {
  weeks: site.last_week,
  lastDate: site.last_date,
  creators: site.creators,
  selections: site.selections,
  mentions: site.mentions,
  perWeek: site.per_week.map((item) => ({w: item.week, sel: item.selected, men: item.mentioned, new: item.new})),
  runs: site.selection_runs.slice(0, 4).map((item) => ({h: item.handle, n: item.length, from: item.from, to: item.to})),
  gap: site.gaps[0],
  tierups: site.tierup_total,
  tierupFaces: site.tierups.slice(0, 12).map((item) => item.handle),
  oneTimers: site.one_timers,
  cameBack: site.came_back,
  mosaic: creators.filter((creator) => available.has(creator.display_handle.toLowerCase())).slice(0, 128)
    .map((creator) => ({h: creator.display_handle, once: weeks(creator).size === 1})),
  hasAvatar,
  week22: {
    week: 22,
    date: site.per_week.find((item) => item.week === 22).date,
    selected: namesFor('spotlight'),
    mentions: namesFor('honourable_mention'),
    newNames: current.filter((creator) => !creator.contributions.some((item) => item.week_label < 22))
      .map((creator) => `@${creator.display_handle}`),
    records: {
      nyuella: record('nyuella'), legend: record('legendary54321'),
      aditya: record('adityapunk01'), bilal: record('bilalearn'),
    },
    endedFiveWeekAppearances,
  },
};
assert.equal(stats.week22.selected.length, 5);
assert.equal(stats.week22.mentions.length, 20);
assert.equal(stats.week22.newNames.length, site.per_week.find((item) => item.week === 22).new);
assert.equal(stats.week22.endedFiveWeekAppearances.length, 3);
await writeFile(resolve(root, 'src/statsData.ts'),
  '/* Generated by scripts/sync-data.mjs from audited site/data/stats.json and seed.json. */\n' +
  `export const STATS = ${JSON.stringify(stats, null, 2)} as const;\n`);
console.log(JSON.stringify({dataDir, totals: {
  weeks: stats.weeks, activeCreators: stats.creators, selections: stats.selections, mentions: stats.mentions,
}, week22New: stats.week22.newNames.length, gap: stats.gap, copiedAvatars: copied, mosaic: stats.mosaic.length}, null, 2));
