/* Generated by scripts/sync-data.mjs from audited site/data/stats.json and seed.json. */
export const STATS = {
  "weeks": 22,
  "lastDate": "2026-10-04",
  "creators": 178,
  "selections": 109,
  "mentions": 279,
  "perWeek": [
    {
      "w": 1,
      "sel": 5,
      "men": 1,
      "new": 6
    },
    {
      "w": 2,
      "sel": 4,
      "men": 5,
      "new": 8
    },
    {
      "w": 3,
      "sel": 5,
      "men": 4,
      "new": 7
    },
    {
      "w": 4,
      "sel": 5,
      "men": 7,
      "new": 9
    },
    {
      "w": 5,
      "sel": 5,
      "men": 10,
      "new": 8
    },
    {
      "w": 6,
      "sel": 4,
      "men": 10,
      "new": 10
    },
    {
      "w": 7,
      "sel": 5,
      "men": 12,
      "new": 10
    },
    {
      "w": 8,
      "sel": 5,
      "men": 12,
      "new": 6
    },
    {
      "w": 9,
      "sel": 5,
      "men": 12,
      "new": 4
    },
    {
      "w": 10,
      "sel": 5,
      "men": 12,
      "new": 6
    },
    {
      "w": 11,
      "sel": 5,
      "men": 12,
      "new": 9
    },
    {
      "w": 12,
      "sel": 4,
      "men": 12,
      "new": 7
    },
    {
      "w": 13,
      "sel": 5,
      "men": 12,
      "new": 9
    },
    {
      "w": 14,
      "sel": 5,
      "men": 14,
      "new": 11
    },
    {
      "w": 15,
      "sel": 4,
      "men": 14,
      "new": 7
    },
    {
      "w": 16,
      "sel": 5,
      "men": 16,
      "new": 7
    },
    {
      "w": 17,
      "sel": 5,
      "men": 18,
      "new": 6
    },
    {
      "w": 18,
      "sel": 5,
      "men": 20,
      "new": 12
    },
    {
      "w": 19,
      "sel": 5,
      "men": 18,
      "new": 9
    },
    {
      "w": 20,
      "sel": 5,
      "men": 20,
      "new": 7
    },
    {
      "w": 21,
      "sel": 8,
      "men": 18,
      "new": 10
    },
    {
      "w": 22,
      "sel": 5,
      "men": 20,
      "new": 10
    }
  ],
  "runs": [
    {
      "h": "Nyuella",
      "n": 5,
      "from": 17,
      "to": 21
    },
    {
      "h": "legendary54321",
      "n": 4,
      "from": 18,
      "to": 21
    },
    {
      "h": "shantelledore",
      "n": 3,
      "from": 15,
      "to": 17
    },
    {
      "h": "Sarcastic_AU",
      "n": 3,
      "from": 13,
      "to": 15
    }
  ],
  "gap": {
    "handle": "Iamolaniyi_",
    "weeks": 14,
    "from": 5,
    "back": 20
  },
  "tierups": 14,
  "tierupFaces": [
    "oldazukii",
    "illfated_fr",
    "legendary54321",
    "Cryptomate3",
    "bruno_jr_talent",
    "aminkaktos2015",
    "kyBellato",
    "NewKO20110815",
    "Sam_wolf1122",
    "likith6150470",
    "itsmahi778",
    "oxkimia"
  ],
  "oneTimers": 79,
  "cameBack": 99,
  "mosaic": [
    {
      "h": "eam__sha",
      "once": false
    },
    {
      "h": "Nyuella",
      "once": false
    },
    {
      "h": "shantelledore",
      "once": false
    },
    {
      "h": "sn0wflakk",
      "once": false
    },
    {
      "h": "legendary54321",
      "once": false
    },
    {
      "h": "DEE_0125",
      "once": false
    },
    {
      "h": "oxkimia",
      "once": false
    },
    {
      "h": "cd_sh51200",
      "once": false
    },
    {
      "h": "Prince_swago",
      "once": false
    },
    {
      "h": "Sarcastic_AU",
      "once": false
    },
    {
      "h": "mr_satoshiii",
      "once": false
    },
    {
      "h": "themoewithin",
      "once": false
    },
    {
      "h": "bruno_jr_talent",
      "once": false
    },
    {
      "h": "NewKO20110815",
      "once": false
    },
    {
      "h": "SAH4R_CORE",
      "once": false
    },
    {
      "h": "0x_Angelarts",
      "once": false
    },
    {
      "h": "Ati43604",
      "once": false
    },
    {
      "h": "kyBellato",
      "once": false
    },
    {
      "h": "salmahshh",
      "once": false
    },
    {
      "h": "sazexbt",
      "once": false
    },
    {
      "h": "Bilalearn",
      "once": false
    },
    {
      "h": "Web3barbiee",
      "once": false
    },
    {
      "h": "illfated_fr",
      "once": false
    },
    {
      "h": "ItsVj786",
      "once": false
    },
    {
      "h": "Wishi007",
      "once": false
    },
    {
      "h": "aminkaktos2015",
      "once": false
    },
    {
      "h": "ashish258042",
      "once": false
    },
    {
      "h": "Cryptomate3",
      "once": false
    },
    {
      "h": "fathy_sol",
      "once": false
    },
    {
      "h": "ishuverse0",
      "once": false
    },
    {
      "h": "likith6150470",
      "once": false
    },
    {
      "h": "__LuckyGold",
      "once": false
    },
    {
      "h": "CaptainMarval08",
      "once": false
    },
    {
      "h": "itsmahi778",
      "once": false
    },
    {
      "h": "barrandland",
      "once": false
    },
    {
      "h": "Chidimm06",
      "once": false
    },
    {
      "h": "CryptoFox_07",
      "once": false
    },
    {
      "h": "hoper0x",
      "once": false
    },
    {
      "h": "Iamolaniyi_",
      "once": false
    },
    {
      "h": "mamatomtn20aprl",
      "once": false
    },
    {
      "h": "mcrypticvolt",
      "once": false
    },
    {
      "h": "Monwilliams001",
      "once": false
    },
    {
      "h": "oldazukii",
      "once": false
    },
    {
      "h": "OneKiwi83488",
      "once": false
    },
    {
      "h": "Sam_wolf1122",
      "once": false
    },
    {
      "h": "Tipwotip",
      "once": false
    },
    {
      "h": "0maxxdev",
      "once": true
    },
    {
      "h": "0truealpha",
      "once": true
    },
    {
      "h": "0xMerajj",
      "once": true
    },
    {
      "h": "aimansheikhh03",
      "once": true
    },
    {
      "h": "beatrice2425",
      "once": true
    },
    {
      "h": "Bitbox50",
      "once": true
    },
    {
      "h": "BLOCK_BUSTER26",
      "once": true
    },
    {
      "h": "c0rishere",
      "once": true
    },
    {
      "h": "edward_evm",
      "once": true
    },
    {
      "h": "HyderShav",
      "once": true
    },
    {
      "h": "Manazrealfact",
      "once": true
    },
    {
      "h": "navdeep_bh1414",
      "once": true
    },
    {
      "h": "Osita__1",
      "once": true
    },
    {
      "h": "ox_elfawzan",
      "once": true
    },
    {
      "h": "Paradise__12345",
      "once": true
    },
    {
      "h": "Sadnoboy616",
      "once": true
    },
    {
      "h": "thesarimzaidi",
      "once": true
    },
    {
      "h": "Tina__bellina",
      "once": true
    },
    {
      "h": "VladisChernov",
      "once": true
    },
    {
      "h": "cryptomasterAJ",
      "once": false
    },
    {
      "h": "Adityapunk01",
      "once": false
    },
    {
      "h": "Avinash_3107",
      "once": false
    },
    {
      "h": "jaymieolamide",
      "once": false
    },
    {
      "h": "143Emile",
      "once": false
    },
    {
      "h": "B0laji_0",
      "once": false
    },
    {
      "h": "chetan0x1",
      "once": false
    },
    {
      "h": "Dredd_the_001",
      "once": false
    },
    {
      "h": "Faizan626371",
      "once": false
    },
    {
      "h": "IluRk123",
      "once": false
    },
    {
      "h": "lavender7888",
      "once": false
    },
    {
      "h": "Moraxweb3",
      "once": false
    },
    {
      "h": "Tochiii184",
      "once": false
    },
    {
      "h": "Vecna071",
      "once": false
    },
    {
      "h": "27_bishal",
      "once": false
    },
    {
      "h": "AsadMalikFromPK",
      "once": false
    },
    {
      "h": "butteryconcept",
      "once": false
    },
    {
      "h": "Dukesznn_eth",
      "once": false
    },
    {
      "h": "itszimal_",
      "once": false
    },
    {
      "h": "izvhee",
      "once": false
    },
    {
      "h": "L1quidLoom",
      "once": false
    },
    {
      "h": "lisa6616393",
      "once": false
    },
    {
      "h": "lyriaa_tv",
      "once": false
    },
    {
      "h": "rira20233",
      "once": false
    },
    {
      "h": "sadegh4222",
      "once": false
    },
    {
      "h": "silvy_1111",
      "once": false
    },
    {
      "h": "SurabhiXNezuko",
      "once": false
    },
    {
      "h": "aayxx5h",
      "once": false
    },
    {
      "h": "Ashii_onchain",
      "once": false
    },
    {
      "h": "Azade7585542676",
      "once": false
    },
    {
      "h": "ByronDrift",
      "once": false
    },
    {
      "h": "captainsilv3r",
      "once": false
    },
    {
      "h": "creativecat3432",
      "once": false
    },
    {
      "h": "CrypticSgr",
      "once": false
    },
    {
      "h": "HarisAl07133821",
      "once": false
    },
    {
      "h": "Harshzzzzzz",
      "once": false
    },
    {
      "h": "joloforU",
      "once": false
    },
    {
      "h": "Kan_maomao",
      "once": false
    },
    {
      "h": "kati9449",
      "once": false
    },
    {
      "h": "lindsey47893795",
      "once": false
    },
    {
      "h": "LUCKYlaku25",
      "once": false
    },
    {
      "h": "luseeferr",
      "once": false
    },
    {
      "h": "maniking5566",
      "once": false
    },
    {
      "h": "MukeshR70147",
      "once": false
    },
    {
      "h": "Naz___a",
      "once": false
    },
    {
      "h": "om_web3",
      "once": false
    },
    {
      "h": "Pawan2001564157",
      "once": false
    },
    {
      "h": "Proof__Seeker",
      "once": false
    },
    {
      "h": "samuelonweb3",
      "once": false
    },
    {
      "h": "soalkcurve",
      "once": false
    },
    {
      "h": "VibinCryptoplus",
      "once": false
    },
    {
      "h": "Web3Radha",
      "once": false
    },
    {
      "h": "zeynabdamilola",
      "once": false
    },
    {
      "h": "0x_amanxbt",
      "once": true
    },
    {
      "h": "0xchlorinee",
      "once": true
    },
    {
      "h": "0xFifth",
      "once": true
    },
    {
      "h": "0xMerajjj",
      "once": true
    },
    {
      "h": "0xnagii",
      "once": true
    },
    {
      "h": "0xrnjbr",
      "once": true
    },
    {
      "h": "0xtheshai",
      "once": true
    },
    {
      "h": "0xwakes",
      "once": true
    },
    {
      "h": "1Depixel",
      "once": true
    },
    {
      "h": "_iamfaramade",
      "once": true
    }
  ],
  "hasAvatar": [
    "0maxxdev",
    "0truealpha",
    "0x_amanxbt",
    "0x_angelarts",
    "0xchlorinee",
    "0xfifth",
    "0xmerajj",
    "0xmerajjj",
    "0xnagii",
    "0xrnjbr",
    "0xtheshai",
    "0xwakes",
    "143emile",
    "1depixel",
    "27_bishal",
    "__luckygold",
    "_iamfaramade",
    "aayxx5h",
    "adityapunk01",
    "aimansheikhh03",
    "ali_zifar7519",
    "amijun7444",
    "aminkaktos2015",
    "amircry94432508",
    "amirirh1",
    "ansarisiddiq876",
    "ara_draww",
    "arian54t",
    "asadmalikfrompk",
    "ashii_onchain",
    "ashish258042",
    "asumaa123",
    "ati43604",
    "avinash_3107",
    "azade7585542676",
    "b0laji_0",
    "barrandland",
    "beatrice2425",
    "behtin6",
    "bilalearn",
    "bitbox50",
    "bivaventures",
    "block_buster26",
    "boss000026",
    "bruno_jr_talent",
    "butteryconcept",
    "byrondrift",
    "bytewave01",
    "c0rishere",
    "captainmarval08",
    "captainsilv3r",
    "cccroshan",
    "cd_sh51200",
    "chetan0x1",
    "chidimm06",
    "creativecat3432",
    "crypticsgr",
    "cryptofox_07",
    "cryptomasteraj",
    "cryptomate3",
    "dalsahab3",
    "dee_0125",
    "dheeraj_805",
    "doctordynamite3",
    "dredd_the_001",
    "dukesznn_eth",
    "eam__sha",
    "edward_evm",
    "faizan626371",
    "fathy_sol",
    "fatimasaud95",
    "godabeg_lee",
    "harisal07133821",
    "harshzzzzzz",
    "hassankhan96452",
    "hawk_tyt",
    "hoper0x",
    "horriyasha01",
    "hottkeed",
    "huzaif066",
    "hydershav",
    "iamolaniyi_",
    "ibrahimawwalol1",
    "illfated_fr",
    "ilurk123",
    "imanntz44",
    "ishaqxx3",
    "ishuverse0",
    "itsmahi778",
    "itsvj786",
    "itszimal_",
    "izvhee",
    "jaymieolamide",
    "joloforu",
    "jugganali236452",
    "kan_maomao",
    "kati9449",
    "katitune25960",
    "khatere_bazi",
    "kybellato",
    "l1quidloom",
    "lavender7888",
    "legendary54321",
    "likith6150470",
    "lindsey47893795",
    "lisa6616393",
    "lone_faizal",
    "luckylaku25",
    "luseeferr",
    "lyriaa_tv",
    "mamatomtn20aprl",
    "manazrealfact",
    "maniking5566",
    "mcrypticvolt",
    "merchanttotoro",
    "mlvmahdii",
    "mohitkhan777",
    "monwilliams001",
    "moraxweb3",
    "mr_joker717",
    "mr_satoshiii",
    "mukeshr70147",
    "muna665830",
    "mzain_2292",
    "navdeep_bh1414",
    "naz___a",
    "newko20110815",
    "nisar_khisrow",
    "nyuella",
    "oggrinding",
    "oldazukii",
    "om_web3",
    "onekiwi83488",
    "osita__1",
    "ox_elfawzan",
    "oxkimia",
    "paradise__12345",
    "pawan2001564157",
    "preshyfoot76257",
    "prince_swago",
    "proof__seeker",
    "rira20233",
    "rose320141",
    "sadegh4222",
    "sadnoboy616",
    "sah4r_core",
    "salmahshh",
    "sam_wolf1122",
    "samiradavodi",
    "samuelonweb3",
    "sarcastic_au",
    "sazexbt",
    "shantelledore",
    "silvy_1111",
    "sinthiya908",
    "siri_210",
    "sn0wflakk",
    "soalkcurve",
    "soha_thk",
    "sun_sea2000",
    "surabhixnezuko",
    "sydneysundown",
    "themoewithin",
    "thesarimzaidi",
    "tina__bellina",
    "tipwotip",
    "tochiii184",
    "vaultvanec0sk",
    "vecna071",
    "vibincryptoplus",
    "vladischernov",
    "web3barbiee",
    "web3radha",
    "wedrick126807",
    "wishi007",
    "wizzy204_",
    "yawem_web",
    "zeynabdamilola"
  ],
  "week22": {
    "week": 22,
    "date": "2026-10-04",
    "selected": [
      "@salmahshh",
      "@Bilalearn",
      "@barrandland",
      "@Manazrealfact",
      "@ox_elfawzan"
    ],
    "mentions": [
      "@illfated_fr",
      "@jaymieolamide",
      "@Faizan626371",
      "@Moraxweb3",
      "@AsadMalikFromPK",
      "@izvhee",
      "@Ashii_onchain",
      "@captainsilv3r",
      "@joloforU",
      "@Naz___a",
      "@samuelonweb3",
      "@soalkcurve",
      "@1Depixel",
      "@ansarisiddiq876",
      "@horriyasha01",
      "@Ishaqxx3",
      "@khatere_bazi",
      "@Mr_Joker717",
      "@Siri_210",
      "@Wizzy204_"
    ],
    "newNames": [
      "@Manazrealfact",
      "@ox_elfawzan",
      "@1Depixel",
      "@ansarisiddiq876",
      "@horriyasha01",
      "@Ishaqxx3",
      "@khatere_bazi",
      "@Mr_Joker717",
      "@Siri_210",
      "@Wizzy204_"
    ],
    "records": {
      "nyuella": {
        "17": "S",
        "18": "S",
        "19": "S",
        "20": "S",
        "21": "S"
      },
      "legend": {
        "17": "m",
        "18": "S",
        "19": "S",
        "20": "S",
        "21": "S"
      },
      "aditya": {
        "17": "m",
        "18": "m",
        "19": "m",
        "20": "m",
        "21": "m"
      },
      "bilal": {
        "21": "S",
        "22": "S"
      }
    },
    "endedFiveWeekAppearances": [
      "Nyuella",
      "legendary54321",
      "Adityapunk01"
    ]
  }
} as const;
