#!/usr/bin/env python3
"""
Fermah Atlas — index the prover node registry.

Reads OperatorRegistered / OperatorAdded style events from the Fermah AVS
registry contract and writes site/data/operators.js. Nothing is invented: give
it the address and an RPC, and it writes only what the chain returns.

    python tools/fetch_operators.py \
        --rpc https://ethereum-sepolia-rpc.publicnode.com \
        --address 0x... \
        --from-block 0

Find the address in fermah-xyz/avs-metadata, not in a blog post.
"""
import argparse
import datetime as dt
import json
import urllib.request

# keccak256("OperatorRegistered(address,bytes32)") and the plain variant;
# add whichever the contract actually emits.
TOPICS = {
    "OperatorRegistered(address,bytes32)":
        "0x8e8485583a2310d41f7c82b9427d0bd49bad74bb9cff9d3402a29d8f9b28a0e2",
    "OperatorAdded(address)":
        "0xac6fa858e9350a46cec16539926e0fde25b7629f84b5a72bffaae4df888ae86d",
}


def rpc(url, method, params):
    req = urllib.request.Request(
        url, headers={"Content-Type": "application/json"},
        data=json.dumps({"jsonrpc": "2.0", "id": 1,
                         "method": method, "params": params}).encode())
    with urllib.request.urlopen(req, timeout=30) as r:
        out = json.load(r)
    if "error" in out:
        raise SystemExit(f"rpc error: {out['error']}")
    return out["result"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rpc", required=True)
    ap.add_argument("--address", required=True, help="AVS registry / service manager")
    ap.add_argument("--from-block", default="0x0")
    ap.add_argument("--network", default="sepolia")
    ap.add_argument("--out", default="site/data/operators.js")
    a = ap.parse_args()

    rows, seen = [], set()
    for name, topic in TOPICS.items():
        try:
            logs = rpc(a.rpc, "eth_getLogs", [{
                "address": a.address, "fromBlock": a.from_block,
                "toBlock": "latest", "topics": [topic]}])
        except SystemExit as e:
            print(f"  {name}: {e}")
            continue
        for lg in logs:
            if len(lg["topics"]) < 2:
                continue
            addr = "0x" + lg["topics"][1][-40:]
            if addr in seen:
                continue
            seen.add(addr)
            blk = rpc(a.rpc, "eth_getBlockByNumber", [lg["blockNumber"], False])
            when = dt.datetime.utcfromtimestamp(int(blk["timestamp"], 16)).date().isoformat()
            rows.append({"address": addr, "registered": when, "label": ""})
        print(f"  {name}: {len(logs)} logs")

    rows.sort(key=lambda r: r["registered"])
    payload = {"network": a.network, "service_manager": a.address,
               "fetched": dt.date.today().isoformat(), "rows": rows}
    open(a.out, "w").write(
        "/* Generated by tools/fetch_operators.py — on-chain data only. */\n"
        "window.OPERATORS = " + json.dumps(payload, indent=1) + ";\n")
    print(f"{len(rows)} operators -> {a.out}")


if __name__ == "__main__":
    main()
